language: python
language: python
python:
  - "2.7"
os: linux
virtualenv:
  system_site_packages: true
install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test # or pytest for Python versions 3.6 and higher