assignment:
  frank-wolfe:
    rgap: 1.0e-05
distribution:
  gravity:
    max error: 0.0001
    max iterations: 100
    max trip length: 10000
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations: 5000
system:
  cpus: 8
  default_directory: Y:\DATA\Pedro\Professional\IPEA\Distribuicao\01_DATA
  driving side: left
  report zeros: 1
