assignment:
  frank-wolfe:
    rgap: 1.0e-05
distribution:
  gravity:
    max error: 0.0001
    max iterations: 100
    max trip length: 10000
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations: 5000
system:
  cpus: 4
  default_directory: /media/pedro/LargeDrive/GOOGLE_DRIVES/UCI/DATA/Pedro/AequilibraE/Testing
    data/Assignment testing data/Assignment
  driving side: right
  logging: false
  report zeros: 1
  temp directory: /temp
