assignment:
  frank-wolfe:
    rgap: 1.0e-05
distribution:
  gravity:
    max trip length: 1000
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations: 5000
system:
  cpus: 8
  default_directory: D:/
  report zeros: 1
